// packages/server/test/session-endpoint-mode.test.ts
// ONE-BRAIN LIVE PATH (2026-09-22, docs/plans/2026-09-22-one-brain-live-path.md, Lane B).
// Imports the REAL CallSession and the REAL engine (LAW: never a copy, never the live API) --
// drives it with a FakeAaiSocket the same way packages/server/test/session.test.ts already
// does. Covers `CallSessionOpts.brainMode`, `nextSpokenLine()`, and `awaitCallerUtterance()`.
import { describe, it, expect, vi, afterEach } from 'vitest';
import { MERIDIAN, mockToolResult } from '@countersign/engine';
import type { CallContext, GoalCode, PhrasingGoal, ServerEvent } from '@countersign/engine';
import { CallSession, PLACEHOLDER_GOAL_LINES } from '../src/call/session.js';
import { FakeAaiSocket } from '../src/aai/fake.js';
import recordedStage from '../../engine/corpus/recorded-stage.json' with { type: 'json' };

afterEach(() => {
  vi.useRealTimers();
});

const CALL = recordedStage.call as CallContext;
// The exact-hint codes fsm.ts composes verbatim (§1 step 4 of the plan; five via `goal.hint`,
// ASK_CHALLENGE separately via `goal.challenge.speak`) -- everything else in this test asserts
// against the `PLACEHOLDER_GOAL_LINES` map imported straight from session.ts, never a
// hand-copied string, so this file can never silently drift from what nextSpokenLine() itself
// reads.
const EXACT_HINT_CODES: ReadonlySet<GoalCode> = new Set<GoalCode>([
  'READBACK',
  'RE_ELICIT_AFTER_SWITCH',
  'ELICIT_MISSING_CRITICAL',
  'ELICIT_REQUEST',
  'CLOSE',
]);

/** The same expectation `nextSpokenLine()` itself implements, recomputed independently here
 *  from `goal` alone (never by calling `nextSpokenLine()` a second time) -- proves the method
 *  reads the right field for the right code, rather than merely asserting it against itself. */
function expectedLineFor(goal: PhrasingGoal): string | undefined {
  if (EXACT_HINT_CODES.has(goal.code)) return goal.hint;
  if (goal.code === 'ASK_CHALLENGE') return goal.challenge?.speak ?? PLACEHOLDER_GOAL_LINES.STALL;
  return PLACEHOLDER_GOAL_LINES[goal.code as keyof typeof PLACEHOLDER_GOAL_LINES];
}

function newSession(opts: { aai: FakeAaiSocket; sent: ServerEvent[]; clock: { now: number }; brainMode?: 'legacy' | 'endpoint' }): CallSession {
  return new CallSession({
    session_id: CALL.session_id,
    seed: MERIDIAN,
    call: CALL,
    aai: opts.aai,
    now: () => opts.clock.now,
    onServerEvent: (e) => opts.sent.push(e),
    mock: mockToolResult,
    // `exactOptionalPropertyTypes` (tsconfig): omit the key entirely rather than pass
    // `brainMode: undefined` -- CallSessionOpts.brainMode is `'legacy' | 'endpoint'` optional,
    // not `'legacy' | 'endpoint' | undefined'`.
    ...(opts.brainMode !== undefined ? { brainMode: opts.brainMode } : {}),
  });
}

const CALLER_LINES = (recordedStage.conversation as { id: string; speaker: string; text: string }[]).filter((u) => u.speaker === 'caller');

describe('CallSession — endpoint mode (COUNTERSIGN_BRAIN=endpoint), one-brain live path', () => {
  it('never sends reply.create across the full recorded-stage.json caller conversation, and nextSpokenLine() matches the engine at every step', () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start(); // INTAKE/GREET -- no agent turn simulated here; the connect-time greeting owns this, not the endpoint (fsm.ts's own GREET comment)

    let replyCounter = 0;
    const stepsObserved: { code: GoalCode; goal: PhrasingGoal; line: string | null }[] = [];

    for (const line of CALLER_LINES) {
      clock.now += 3000;
      aai.emit({ type: 'transcript.user', item_id: line.id, text: line.text });

      expect(session.last).not.toBeNull();
      const goal = session.last!.goal;
      const spoken = session.nextSpokenLine();
      stepsObserved.push({ code: goal.code, goal, line: spoken });

      // The one place a real reply.done cycle would matter is READBACK/ELICIT_MISSING_CRITICAL/
      // ASK_CHALLENGE, which need a matching `challenge_issued`/`readback_issued`/`elicit_issued`
      // action logged for the caller's NEXT turn to be read as an answer/confirmation -- in the
      // real one-brain design this comes from AssemblyAI's own genuine reply.started/transcript.
      // agent/reply.done cycle for the automatic reply IT generated by calling our endpoint (never
      // from OUR OWN reply.create, which stays unsent throughout -- that is exactly what this test
      // proves). Echoing `spoken` back as that reply's own transcript is the realistic shape: it is
      // literally what the endpoint would have returned and AssemblyAI would have spoken verbatim.
      if (spoken !== null) {
        replyCounter += 1;
        const replyId = `endpoint-reply-${replyCounter}`;
        clock.now += 500;
        aai.emit({ type: 'reply.started', reply_id: replyId });
        aai.emit({ type: 'transcript.agent', item_id: `${replyId}-t`, text: spoken, reply_id: replyId, interrupted: false });
        aai.emit({ type: 'reply.done', reply_id: replyId, status: 'completed' });
      }
    }

    // The core one-brain claim (plan §2, §6 item 5's grader bar): NOT ONE reply.create, ever,
    // across the whole conversation -- the two-writer race this file's gated methods exist to
    // manage simply never has anything to race.
    expect(aai.sent.some((m) => (m as { type?: string }).type === 'reply.create')).toBe(false);

    // At least one real turn happened (the drive is not a no-op) and every captured line matches
    // the engine's own composed sentence for its goal, independently recomputed above.
    expect(stepsObserved.length).toBe(CALLER_LINES.length);
    for (const step of stepsObserved) {
      expect(step.line).toBe(expectedLineFor(step.goal) ?? null);
    }
  });

  it('nextSpokenLine() returns null before any evaluate() has run (no tick yet)', () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    expect(session.nextSpokenLine()).toBeNull();
  });

  it('nextSpokenLine() is read-only: repeated calls never mutate state or send anything', () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();
    aai.emit({ type: 'transcript.user', item_id: 'c1', text: CALLER_LINES[0]!.text });

    const before = aai.sent.length;
    const a = session.nextSpokenLine();
    const b = session.nextSpokenLine();
    const c = session.nextSpokenLine();
    expect(a).toBe(b);
    expect(b).toBe(c);
    expect(aai.sent.length).toBe(before); // no message was sent just from calling it
  });
});

describe('CallSession — legacy mode (default): unchanged, still sends reply.create', () => {
  it('sends reply.create for the same recorded-stage.json opening line (contrast with endpoint mode above)', () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    // brainMode omitted entirely -- proves the default (legacy) path is what an existing,
    // unmodified caller of CallSession still gets.
    const session = newSession({ aai, sent, clock });
    session.start();

    vi.useFakeTimers();
    clock.now = 1000;
    aai.emit({ type: 'transcript.user', item_id: CALLER_LINES[0]!.id, text: CALLER_LINES[0]!.text });
    // AUTOMATIC_REPLY_SETTLE_MS (150ms) covers the fresh-question deferred send; a generous
    // margin covers either that path or a synchronous forceSpeak send.
    vi.advanceTimersByTime(1000);

    expect(aai.sent.some((m) => (m as { type?: string }).type === 'reply.create')).toBe(true);
  });
});

describe('CallSession#awaitCallerUtterance', () => {
  it('resolves true once the matching transcript.user is dispatched', async () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    const waiting = session.awaitCallerUtterance('This is Dana Whitfield, corporate treasury.', 2000);
    aai.emit({ type: 'transcript.user', item_id: 'c1', text: 'This is Dana Whitfield, corporate treasury.' });
    await expect(waiting).resolves.toBe(true);
  });

  it('exact match after trim on both sides -- surrounding whitespace on either side still matches', async () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    const waiting = session.awaitCallerUtterance('  Yes.  ', 2000);
    aai.emit({ type: 'transcript.user', item_id: 'c1', text: 'Yes.' });
    await expect(waiting).resolves.toBe(true);
  });

  it('resolves true immediately when a matching caller line was already processed before the call', async () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();
    aai.emit({ type: 'transcript.user', item_id: 'c1', text: 'No, it is for Meridian Supply.' });

    await expect(session.awaitCallerUtterance('No, it is for Meridian Supply.', 2000)).resolves.toBe(true);
  });

  it('does not resolve for a non-matching transcript, and resolves false once timeoutMs elapses', async () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    vi.useFakeTimers();
    const waiting = session.awaitCallerUtterance('Yes.', 1000);
    aai.emit({ type: 'transcript.user', item_id: 'c1', text: 'No.' }); // does not match -- must not resolve yet
    await vi.advanceTimersByTimeAsync(999);
    await vi.advanceTimersByTimeAsync(2);
    await expect(waiting).resolves.toBe(false);
  });

  it('two waiters on the same text both resolve from one matching transcript', async () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    const first = session.awaitCallerUtterance('Yes.', 2000);
    const second = session.awaitCallerUtterance('Yes.', 2000);
    aai.emit({ type: 'transcript.user', item_id: 'c1', text: 'Yes.' });
    await expect(first).resolves.toBe(true);
    await expect(second).resolves.toBe(true);
  });
});
