// packages/server/test/session-endpoint-mode.test.ts
// ONE-BRAIN LIVE PATH (2026-09-22, docs/plans/2026-09-22-one-brain-live-path.md, Lane B).
// Imports the REAL CallSession and the REAL engine (LAW: never a copy, never the live API) --
// drives it with a FakeAaiSocket the same way packages/server/test/session.test.ts already
// does. Covers `CallSessionOpts.brainMode`, `nextSpokenLine()`, and `awaitCallerUtterance()`.
import { describe, it, expect, vi, afterEach } from 'vitest';
import { MERIDIAN, mockToolResult } from '@countersign/engine';
import type { CallContext, GoalCode, PhrasingGoal, ServerEvent } from '@countersign/engine';
import { CallSession, PLACEHOLDER_GOAL_LINES } from '../src/call/session.js';
import { FakeAaiSocket } from '../src/aai/fake.js';
import type { AaiEvent } from '../src/aai/types.js';
import recordedStage from '../../engine/corpus/recorded-stage.json' with { type: 'json' };

afterEach(() => {
  vi.useRealTimers();
});

const CALL = recordedStage.call as CallContext;
// The exact-hint codes fsm.ts composes verbatim (§1 step 4 of the plan; five via `goal.hint`,
// ASK_CHALLENGE separately via `goal.challenge.speak`) -- everything else in this test asserts
// against the `PLACEHOLDER_GOAL_LINES` map imported straight from session.ts, never a
// hand-copied string, so this file can never silently drift from what nextSpokenLine() itself
// reads.
const EXACT_HINT_CODES: ReadonlySet<GoalCode> = new Set<GoalCode>([
  'READBACK',
  'RE_ELICIT_AFTER_SWITCH',
  'ELICIT_MISSING_CRITICAL',
  'ELICIT_REQUEST',
  'CLOSE',
]);

/** The same expectation `nextSpokenLine()` itself implements, recomputed independently here
 *  from `goal` alone (never by calling `nextSpokenLine()` a second time) -- proves the method
 *  reads the right field for the right code, rather than merely asserting it against itself. */
function expectedLineFor(goal: PhrasingGoal): string | undefined {
  if (EXACT_HINT_CODES.has(goal.code)) return goal.hint;
  if (goal.code === 'ASK_CHALLENGE') return goal.challenge?.speak ?? PLACEHOLDER_GOAL_LINES.STALL;
  return PLACEHOLDER_GOAL_LINES[goal.code as keyof typeof PLACEHOLDER_GOAL_LINES];
}

function newSession(opts: { aai: FakeAaiSocket; sent: ServerEvent[]; clock: { now: number }; brainMode?: 'legacy' | 'endpoint' }): CallSession {
  return new CallSession({
    session_id: CALL.session_id,
    seed: MERIDIAN,
    call: CALL,
    aai: opts.aai,
    now: () => opts.clock.now,
    onServerEvent: (e) => opts.sent.push(e),
    mock: mockToolResult,
    // `exactOptionalPropertyTypes` (tsconfig): omit the key entirely rather than pass
    // `brainMode: undefined` -- CallSessionOpts.brainMode is `'legacy' | 'endpoint'` optional,
    // not `'legacy' | 'endpoint' | undefined'`.
    ...(opts.brainMode !== undefined ? { brainMode: opts.brainMode } : {}),
  });
}

const CALLER_LINES = (recordedStage.conversation as { id: string; speaker: string; text: string }[]).filter((u) => u.speaker === 'caller');

describe('CallSession — endpoint mode (COUNTERSIGN_BRAIN=endpoint), one-brain live path', () => {
  it('never sends reply.create across the full recorded-stage.json caller conversation, and nextSpokenLine() matches the engine at every step', () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start(); // INTAKE/GREET -- no agent turn simulated here; the connect-time greeting owns this, not the endpoint (fsm.ts's own GREET comment)

    let replyCounter = 0;
    const stepsObserved: { code: GoalCode; goal: PhrasingGoal; line: string | null }[] = [];

    for (const line of CALLER_LINES) {
      clock.now += 3000;
      aai.emit({ type: 'transcript.user', item_id: line.id, text: line.text });

      expect(session.last).not.toBeNull();
      const goal = session.last!.goal;
      const spoken = session.nextSpokenLine();
      stepsObserved.push({ code: goal.code, goal, line: spoken });

      // The one place a real reply.done cycle would matter is READBACK/ELICIT_MISSING_CRITICAL/
      // ASK_CHALLENGE, which need a matching `challenge_issued`/`readback_issued`/`elicit_issued`
      // action logged for the caller's NEXT turn to be read as an answer/confirmation -- in the
      // real one-brain design this comes from AssemblyAI's own genuine reply.started/transcript.
      // agent/reply.done cycle for the automatic reply IT generated by calling our endpoint (never
      // from OUR OWN reply.create, which stays unsent throughout -- that is exactly what this test
      // proves). Echoing `spoken` back as that reply's own transcript is the realistic shape: it is
      // literally what the endpoint would have returned and AssemblyAI would have spoken verbatim.
      if (spoken !== null) {
        replyCounter += 1;
        const replyId = `endpoint-reply-${replyCounter}`;
        clock.now += 500;
        aai.emit({ type: 'reply.started', reply_id: replyId });
        aai.emit({ type: 'transcript.agent', item_id: `${replyId}-t`, text: spoken, reply_id: replyId, interrupted: false });
        aai.emit({ type: 'reply.done', reply_id: replyId, status: 'completed' });
      }
    }

    // The core one-brain claim (plan §2, §6 item 5's grader bar): NOT ONE reply.create, ever,
    // across the whole conversation -- the two-writer race this file's gated methods exist to
    // manage simply never has anything to race.
    expect(aai.sent.some((m) => (m as { type?: string }).type === 'reply.create')).toBe(false);

    // At least one real turn happened (the drive is not a no-op) and every captured line matches
    // the engine's own composed sentence for its goal, independently recomputed above.
    expect(stepsObserved.length).toBe(CALLER_LINES.length);
    for (const step of stepsObserved) {
      expect(step.line).toBe(expectedLineFor(step.goal) ?? null);
    }
  });

  it('nextSpokenLine() returns null before any evaluate() has run (no tick yet)', () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    expect(session.nextSpokenLine()).toBeNull();
  });

  it('nextSpokenLine() is read-only: repeated calls never mutate state or send anything', () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();
    aai.emit({ type: 'transcript.user', item_id: 'c1', text: CALLER_LINES[0]!.text });

    const before = aai.sent.length;
    const a = session.nextSpokenLine();
    const b = session.nextSpokenLine();
    const c = session.nextSpokenLine();
    expect(a).toBe(b);
    expect(b).toBe(c);
    expect(aai.sent.length).toBe(before); // no message was sent just from calling it
  });
});

describe('CallSession — legacy mode (default): unchanged, still sends reply.create', () => {
  it('sends reply.create for the same recorded-stage.json opening line (contrast with endpoint mode above)', () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    // brainMode omitted entirely -- proves the default (legacy) path is what an existing,
    // unmodified caller of CallSession still gets.
    const session = newSession({ aai, sent, clock });
    session.start();

    vi.useFakeTimers();
    clock.now = 1000;
    aai.emit({ type: 'transcript.user', item_id: CALLER_LINES[0]!.id, text: CALLER_LINES[0]!.text });
    // AUTOMATIC_REPLY_SETTLE_MS (150ms) covers the fresh-question deferred send; a generous
    // margin covers either that path or a synchronous forceSpeak send.
    vi.advanceTimersByTime(1000);

    expect(aai.sent.some((m) => (m as { type?: string }).type === 'reply.create')).toBe(true);
  });
});

describe('CallSession#awaitCallerUtterance', () => {
  it('resolves true once the matching transcript.user is dispatched', async () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    const waiting = session.awaitCallerUtterance('This is Dana Whitfield, corporate treasury.', 2000);
    aai.emit({ type: 'transcript.user', item_id: 'c1', text: 'This is Dana Whitfield, corporate treasury.' });
    await expect(waiting).resolves.toBe(true);
  });

  it('exact match after trim on both sides -- surrounding whitespace on either side still matches', async () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    const waiting = session.awaitCallerUtterance('  Yes.  ', 2000);
    aai.emit({ type: 'transcript.user', item_id: 'c1', text: 'Yes.' });
    await expect(waiting).resolves.toBe(true);
  });

  it('resolves true immediately when a matching caller line was already processed before the call', async () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();
    aai.emit({ type: 'transcript.user', item_id: 'c1', text: 'No, it is for Meridian Supply.' });

    await expect(session.awaitCallerUtterance('No, it is for Meridian Supply.', 2000)).resolves.toBe(true);
  });

  it('does not resolve for a non-matching transcript, and resolves false once timeoutMs elapses', async () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    vi.useFakeTimers();
    const waiting = session.awaitCallerUtterance('Yes.', 1000);
    aai.emit({ type: 'transcript.user', item_id: 'c1', text: 'No.' }); // does not match -- must not resolve yet
    await vi.advanceTimersByTimeAsync(999);
    await vi.advanceTimersByTimeAsync(2);
    await expect(waiting).resolves.toBe(false);
  });

  it('two waiters on the same text both resolve from one matching transcript', async () => {
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    const first = session.awaitCallerUtterance('Yes.', 2000);
    const second = session.awaitCallerUtterance('Yes.', 2000);
    aai.emit({ type: 'transcript.user', item_id: 'c1', text: 'Yes.' });
    await expect(first).resolves.toBe(true);
    await expect(second).resolves.toBe(true);
  });
});

// DEAD-AIR-ON-TIMEOUT fix (2026-09-22): brain/endpoint.ts's own `awaitCallerUtterance` wait
// (§1 of the one-brain plan) is bounded at 1500ms; on timeout it answers AssemblyAI with an
// EMPTY completion so it never re-asks the previous question. If the matching `transcript.
// user` then lands anyway, nothing else was ever going to ask our endpoint again for it --
// the caller would hear dead air until they spoke again. This block proves the fix: a late-
// arriving matching transcript, processed AFTER its own tick, gets exactly one `reply.create`
// TRIGGER (`sendEndpointTrigger` -- see its own doc comment for why this is a dedicated
// endpoint-only method, never `sendReplyCreate` itself, which refuses this mode
// unconditionally).
describe('CallSession — endpoint mode: dead-air-on-timeout fix (late transcript after a timed-out awaitCallerUtterance)', () => {
  afterEach(() => {
    vi.useRealTimers();
  });

  it('a timed-out wait followed by the late matching transcript sends exactly one reply.create trigger, after the tick (nextSpokenLine reflects the NEW goal)', async () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    const beforeLine = session.nextSpokenLine();
    const text = CALLER_LINES[0]!.text;
    const waiting = session.awaitCallerUtterance(text, 1500);
    await vi.advanceTimersByTimeAsync(1500);
    await expect(waiting).resolves.toBe(false);

    // The endpoint has already answered empty for this turn -- nothing sent yet.
    expect(aai.sent.some((m) => (m as { type?: string }).type === 'reply.create')).toBe(false);

    // The matching transcript.user lands anyway (AssemblyAI's own delivery, independent of
    // the HTTP request that timed out -- plan §1's "ordering race").
    aai.emit({ type: 'transcript.user', item_id: 'late-1', text });

    const replyCreates = aai.sent.filter((m) => (m as { type?: string }).type === 'reply.create');
    expect(replyCreates.length).toBe(1);
    // No instructions -- the endpoint renders `nextSpokenLine()` itself (plan §1: the trailing
    // system message is a pure TRIGGER, never engine input).
    expect(replyCreates[0]).toEqual({ type: 'reply.create' });

    // Fired AFTER this event's own tick -- nextSpokenLine() now reflects the NEW goal the late
    // transcript produced, not whatever it was before this turn landed.
    expect(session.last).not.toBeNull();
    const afterLine = session.nextSpokenLine();
    expect(afterLine).not.toBe(beforeLine);
    expect(afterLine).toBe(expectedLineFor(session.last!.goal) ?? null);
  });

  it('a normal in-time wait never sends a reply.create trigger', async () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    const text = CALLER_LINES[0]!.text;
    const waiting = session.awaitCallerUtterance(text, 1500);
    await vi.advanceTimersByTimeAsync(200); // comfortably within the 1500ms bound
    aai.emit({ type: 'transcript.user', item_id: 'in-time-1', text });
    await expect(waiting).resolves.toBe(true);

    // Even once the original timeout would otherwise have elapsed, still nothing -- it never
    // actually timed out, so nothing was ever recorded to trigger on.
    await vi.advanceTimersByTimeAsync(2000);
    expect(aai.sent.some((m) => (m as { type?: string }).type === 'reply.create')).toBe(false);
  });

  it('two INDEPENDENT timed-out utterances -- each one\'s own timeout and late arrival, with nothing else happening in between -- each get their own trigger', async () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    const textA = CALLER_LINES[0]!.text;
    const textB = CALLER_LINES[1]!.text;
    expect(textA).not.toBe(textB);
    const replyCreateCount = (): number => aai.sent.filter((m) => (m as { type?: string }).type === 'reply.create').length;

    // A: times out, then lands late, fully resolved (its own trigger fires) BEFORE B's own
    // wait even starts -- each utterance's timeout/late-arrival pair is independent, nothing
    // of B's is straddling A's window (that straddling case is its own test below).
    const waitingA = session.awaitCallerUtterance(textA, 1500);
    await vi.advanceTimersByTimeAsync(1500);
    await expect(waitingA).resolves.toBe(false);
    aai.emit({ type: 'transcript.user', item_id: 'late-a', text: textA });
    expect(replyCreateCount()).toBe(1);

    // B: its OWN wait starts only now (its `callerTurnCountAtTimeout`/`replyStartedSeqAtTimeout`
    // snapshot is taken AFTER A has already fully resolved), times out, then lands late with
    // nothing else in between -- its own, independent second trigger.
    const waitingB = session.awaitCallerUtterance(textB, 1500);
    await vi.advanceTimersByTimeAsync(1500);
    await expect(waitingB).resolves.toBe(false);
    aai.emit({ type: 'transcript.user', item_id: 'late-b', text: textB });
    expect(replyCreateCount()).toBe(2);
  });

  it('the same utterance landing twice (a genuine repeat, fresh item_id) never gets a second trigger', async () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    const text = CALLER_LINES[0]!.text;
    const replyCreateCount = (): number => aai.sent.filter((m) => (m as { type?: string }).type === 'reply.create').length;

    const waiting = session.awaitCallerUtterance(text, 1500);
    await vi.advanceTimersByTimeAsync(1500);
    await expect(waiting).resolves.toBe(false);

    aai.emit({ type: 'transcript.user', item_id: 'late-1', text });
    expect(replyCreateCount()).toBe(1);

    // The caller repeats the exact same words later (a fresh item_id) -- the timed-out record
    // for this text was already consumed by the trigger above ("never trigger more than once
    // per timed-out utterance"), so this must NOT add a second one.
    aai.emit({ type: 'transcript.user', item_id: 'repeat-1', text });
    expect(replyCreateCount()).toBe(1);
  });

  // STALE-TRIGGER fix (2026-09-22 review, BLOCKING on the first cut of this fix): the exact
  // scenario review flagged. A's wait times out (empty completion); before A's own transcript
  // ever lands, the caller -- hearing dead air -- speaks again (B), a genuinely NEWER turn
  // that gets its own correct render through AssemblyAI's normal turn-driven flow (simulated
  // below the same way the top describe block's own drive loop echoes AssemblyAI's automatic
  // reply back). Only THEN does A's own transcript.user land late. Firing a trigger for A now
  // would talk over or supersede B's already-delivered render -- the exact repeated-question/
  // talk-over class this project has hit live repeatedly (docs/AUTOPILOT_LOG.md, Day 4-13).
  // Must produce ZERO triggers.
  it("a newer caller turn (B) landing after A's timeout but before A's late transcript suppresses A's trigger entirely (never talks over B's own render)", async () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    const textA = CALLER_LINES[0]!.text;
    const textB = CALLER_LINES[1]!.text;
    expect(textA).not.toBe(textB);

    const waitingA = session.awaitCallerUtterance(textA, 1500);
    await vi.advanceTimersByTimeAsync(1500);
    await expect(waitingA).resolves.toBe(false);
    expect(aai.sent.some((m) => (m as { type?: string }).type === 'reply.create')).toBe(false);

    // B lands and gets its own normal render (AssemblyAI's own automatic reply, echoed back
    // exactly as the top describe block's drive loop does) -- NOT a trigger of ours; endpoint
    // mode never sends reply.create for an ordinary turn.
    aai.emit({ type: 'transcript.user', item_id: 'b-1', text: textB });
    const bLine = session.nextSpokenLine();
    expect(bLine).not.toBeNull();
    aai.emit({ type: 'reply.started', reply_id: 'b-reply' });
    aai.emit({ type: 'transcript.agent', item_id: 'b-reply-t', text: bLine!, reply_id: 'b-reply', interrupted: false });
    aai.emit({ type: 'reply.done', reply_id: 'b-reply', status: 'completed' });
    expect(aai.sent.some((m) => (m as { type?: string }).type === 'reply.create')).toBe(false);

    // A's own transcript.user now finally lands, stale -- must be dropped silently.
    aai.emit({ type: 'transcript.user', item_id: 'a-late', text: textA });

    expect(aai.sent.some((m) => (m as { type?: string }).type === 'reply.create')).toBe(false);
  });

  it('a matching transcript that arrives after end() never sends a trigger', async () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();

    const text = CALLER_LINES[0]!.text;
    const waiting = session.awaitCallerUtterance(text, 1500);
    await vi.advanceTimersByTimeAsync(1500);
    await expect(waiting).resolves.toBe(false);

    session.end('test_dead_air_after_end');
    const sentBefore = aai.sent.length;

    // FakeAaiSocket.emit() itself no-ops once closed (aai.close() runs inside end()), matching
    // how the real transport would behave -- so this reaches the private dispatch path
    // directly (the same technique this file's legacy-mode CLOSE test already uses for
    // `scheduleCloseIfNeeded`) purely to prove `sendEndpointTrigger`'s own `this.ended` guard
    // and `timedOutCallerUtterances`'s clear-on-`end()`, not to claim this path is reachable
    // live through an already-closed socket.
    const internals = session as unknown as { dispatchAaiEvent: (evt: AaiEvent) => void };
    internals.dispatchAaiEvent({ type: 'transcript.user', item_id: 'late-after-end', text });

    expect(aai.sent.length).toBe(sentBefore);
    expect(aai.sent.some((m) => (m as { type?: string }).type === 'reply.create')).toBe(false);
  });

  it("legacy mode (brainMode omitted): a timed-out awaitCallerUtterance wait followed by the matching transcript adds no EXTRA reply.create beyond legacy's own unchanged flow", async () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock }); // brainMode omitted -- legacy, the default
    session.start();

    const text = CALLER_LINES[0]!.text;
    const waiting = session.awaitCallerUtterance(text, 1500);
    await vi.advanceTimersByTimeAsync(1500);
    await expect(waiting).resolves.toBe(false);

    aai.emit({ type: 'transcript.user', item_id: CALLER_LINES[0]!.id, text });
    // AUTOMATIC_REPLY_SETTLE_MS covers legacy's own deferred send for a fresh question.
    await vi.advanceTimersByTimeAsync(1000);

    // Legacy still sends exactly the ONE reply.create its own pre-existing machinery always
    // sent for this turn -- `sendEndpointTrigger` is gated on `brainMode === 'endpoint'` and
    // never fires here, so this proves the fix adds no second, extra send in legacy mode.
    const replyCreates = aai.sent.filter((m) => (m as { type?: string }).type === 'reply.create');
    expect(replyCreates.length).toBe(1);
  });
});

// ONE-BRAIN LIVE PATH, review finding on commit c73ae21: in endpoint mode every method that
// manages the LEGACY two-writer race (`maybeArmCloseOnTranscript`, `armCloseTranscriptWait`,
// `scheduleCloseIfNeeded`) early-returns -- correct, since endpoint mode has exactly one
// writer (AssemblyAI's own automatic reply IS our `/api/brain` endpoint's words, by
// construction) -- but those three are ALSO the only callers of `beginCloseGrace`. With
// nothing left to call it, an endpoint-mode call that reaches its verdict, speaks the
// verdict+goodbye line, never hangs up until the 45s `CLOSE_TOTAL_MS` hard cap
// (`armClose`, unconditional -- fires regardless of `brainMode`, see `applyEvaluate`'s
// goal-changed branch). This describe block proves the fix: once the goal is CLOSE and the
// close line's OWN `reply.done` has arrived with a transcript that matches it
// (`transcriptMatchesCloseSentence`, the existing DETECTOR, never a sender), the call ends a
// few seconds later -- `CLOSE_GRACE_MS` (1500ms, session.ts), the exact same constant and
// mechanism (`beginCloseGrace`) legacy mode's own heard-goodbye hangup already uses (see
// session.test.ts's "ends the call reason 'agent_closed' a short grace period after the
// CLOSE reply completes").
describe('CallSession — endpoint mode: closes the call after the goodbye is heard (review finding on c73ae21)', () => {
  afterEach(() => {
    vi.useRealTimers();
  });

  /** Drives CALLER_LINES[0..3] (identity, switch, amount, account confirmations -- every
   *  caller line in recorded-stage.json EXCEPT the final beneficiary confirmation) through
   *  the exact echo pattern the top describe block's own first test uses: emit the caller's
   *  real line, read `nextSpokenLine()` for the goal the REAL engine just rendered, echo it
   *  back as the reply AssemblyAI's own automatic turn would have produced. Leaves the
   *  session one caller turn away from the STAGE verdict's CLOSE goal, so each test below
   *  drives that final turn itself and takes full control of the close line's own
   *  transcript.agent/reply.done timing. */
  function driveToOneTurnBeforeClose(session: CallSession, aai: FakeAaiSocket, clock: { now: number }): void {
    let replyCounter = 0;
    for (const line of CALLER_LINES.slice(0, -1)) {
      clock.now += 3000;
      aai.emit({ type: 'transcript.user', item_id: line.id, text: line.text });
      const spoken = session.nextSpokenLine();
      expect(spoken).not.toBeNull();
      replyCounter += 1;
      const replyId = `pre-close-reply-${replyCounter}`;
      clock.now += 500;
      aai.emit({ type: 'reply.started', reply_id: replyId });
      aai.emit({ type: 'transcript.agent', item_id: `${replyId}-t`, text: spoken!, reply_id: replyId, interrupted: false });
      aai.emit({ type: 'reply.done', reply_id: replyId, status: 'completed' });
    }
  }

  // GOODBYE-CUT-BY-CALLER-PRESSURE, mirrored from legacy (2026-09-22 review of the first
  // cut of the fix above -- BLOCKING): `closeReplyHasEnoughAudio`'s own floor formula
  // (session.ts ~494-533), re-declared here the same way this file already re-declares
  // other private statics as local consts (e.g. `REASK_GAP_MS` in session.test.ts).
  const CLOSE_AUDIO_BYTES_PER_CHAR = 4_000; // CallSession.CLOSE_AUDIO_BYTES_PER_CHAR
  const CLOSE_AUDIO_FLOOR_FRACTION = 0.5; // CallSession.CLOSE_AUDIO_FLOOR_FRACTION
  const OUTPUT_AUDIO_BYTES_PER_SECOND = 48_000; // CallSession.OUTPUT_AUDIO_BYTES_PER_SECOND
  function audioBytesFor(sentence: string, fraction: number): number {
    return Math.round(sentence.length * CLOSE_AUDIO_BYTES_PER_CHAR * fraction);
  }
  /** How long `bytes` of relayed audio takes to play, in ms -- `beginCloseGrace`'s own
   *  audio-aware deadline (session.ts) folds this into its wait, so a test that emits real
   *  audio bytes for the close reply must let at least this much (simulated) clock.now time
   *  pass before `reply.done` for the flat CLOSE_GRACE_MS to be the thing actually governing
   *  the final wait -- exactly the reasoning session.test.ts's own CLOSE-hangup tests already
   *  document inline (e.g. "audio-based deadline 7500+4000+1000=12500"). */
  function audioPlaybackMs(bytes: number): number {
    return (bytes / OUTPUT_AUDIO_BYTES_PER_SECOND) * 1000;
  }

  it("ends the call within CLOSE_GRACE_MS of the close line's own reply.done, not the 45s CLOSE_TOTAL_MS cap (c: full audio relayed)", () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();
    driveToOneTurnBeforeClose(session, aai, clock);

    const lastLine = CALLER_LINES.at(-1)!;
    clock.now += 3000;
    aai.emit({ type: 'transcript.user', item_id: lastLine.id, text: lastLine.text });

    // The real engine, driven by the real recorded-stage.json corpus, has reached the STAGE
    // verdict's terminal CLOSE goal -- not a forced/synthetic state.
    expect(session.last?.verdict).toBe('STAGE');
    expect(session.last?.goal.code).toBe('CLOSE');
    const closeSentence = session.nextSpokenLine();
    expect(closeSentence).toBe(session.last!.goal.hint);

    clock.now += 500;
    aai.emit({ type: 'reply.started', reply_id: 'close-reply' });
    // Full expected audio (100% of CLOSE_AUDIO_BYTES_PER_CHAR) -- comfortably clears
    // closeReplyHasEnoughAudio's 50% floor, same margin session.test.ts's own CLOSE tests use.
    const closeAudioBytes = audioBytesFor(closeSentence!, 1.0);
    aai.emit({ type: 'reply.audio', data: Buffer.alloc(closeAudioBytes).toString('base64') });
    aai.emit({ type: 'transcript.agent', item_id: 'close-t', text: closeSentence!, reply_id: 'close-reply', interrupted: false });

    // One-brain invariant, unaffected by this fix: never a reply.create, in endpoint mode,
    // for any turn including the close line itself.
    expect(aai.sent.some((m) => (m as { type?: string }).type === 'reply.create')).toBe(false);
    expect(aai.isClosed).toBe(false);

    // reply.done lands only after this audio would have finished streaming (same reasoning
    // session.test.ts's own CLOSE-hangup tests use) -- so the flat CLOSE_GRACE_MS, not the
    // audio-aware deadline, is what governs the final wait asserted below.
    clock.now += Math.ceil(audioPlaybackMs(closeAudioBytes)) + 100;
    aai.emit({ type: 'reply.done', reply_id: 'close-reply', status: 'completed' });

    // Not ended the instant reply.done arrives -- the same short grace period legacy mode
    // uses lets the goodbye's own audio finish reaching the wire before the socket closes.
    expect(sent.some((e) => e.type === 'ended')).toBe(false);
    expect(aai.isClosed).toBe(false);

    // CLOSE_GRACE_MS = 1500 (session.ts, private static, reused here as a literal the same
    // way session.test.ts's own CLOSE-hangup tests already do).
    vi.advanceTimersByTime(1499);
    expect(sent.some((e) => e.type === 'ended')).toBe(false);
    expect(aai.isClosed).toBe(false);
    vi.advanceTimersByTime(1);
    expect(sent.at(-1)).toEqual({ type: 'ended', reason: 'agent_closed' });
    expect(aai.isClosed).toBe(true);

    // Nowhere near the 45s CLOSE_TOTAL_MS hard cap this bug used to fall all the way through
    // to -- advancing well past it must not produce a second 'ended' (idempotent either way,
    // but this proves the hard cap was actually cancelled, not just masked).
    const endedCountBefore = sent.filter((e) => e.type === 'ended').length;
    vi.advanceTimersByTime(45_000);
    expect(sent.filter((e) => e.type === 'ended').length).toBe(endedCountBefore);
  });

  // GOODBYE-CUT-BY-CALLER-PRESSURE, mirrored from legacy (2026-09-22 review, BLOCKING on the
  // first cut of the fix above): a transcript match is never enough on its own -- two PROVEN
  // live incidents (closeReplyHasEnoughAudio's own doc comment, session.ts ~494-533) are
  // SINGLE-reply transcript/audio divergences, not two-writer artifacts, and reply.audio
  // accounting is identical in both modes -- so endpoint mode needs the exact same floor.
  it('(a) an interrupted close reply whose transcript is full but the relayed audio is below the floor never starts the close grace', () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();
    driveToOneTurnBeforeClose(session, aai, clock);

    const lastLine = CALLER_LINES.at(-1)!;
    clock.now += 3000;
    aai.emit({ type: 'transcript.user', item_id: lastLine.id, text: lastLine.text });
    expect(session.last?.goal.code).toBe('CLOSE');
    const closeSentence = session.nextSpokenLine()!;

    clock.now += 500;
    aai.emit({ type: 'reply.started', reply_id: 'close-reply' });
    // ~11% of expected bytes -- mirrors the live incident where a caller barge-in cut a
    // CLOSE reply to "This..." (37,920/86 chars, 11.0%) while its own transcript.agent chunk
    // had already carried the FULL sentence.
    aai.emit({ type: 'reply.audio', data: Buffer.alloc(audioBytesFor(closeSentence, 0.11)).toString('base64') });
    aai.emit({ type: 'transcript.agent', item_id: 'close-t', text: closeSentence, reply_id: 'close-reply', interrupted: true });
    clock.now += 100;
    aai.emit({ type: 'reply.done', reply_id: 'close-reply', status: 'interrupted' });

    // No close grace started -- well past CLOSE_GRACE_MS (1500ms), still not ended.
    vi.advanceTimersByTime(5000);
    expect(sent.some((e) => e.type === 'ended')).toBe(false);
    expect(aai.isClosed).toBe(false);

    // The unconditional 45s CLOSE_TOTAL_MS hard cap remains the backstop, unchanged.
    vi.advanceTimersByTime(40_000);
    expect(sent.at(-1)).toEqual({ type: 'ended', reason: 'close_timeout' });
    expect(aai.isClosed).toBe(true);
  });

  it('(b) a completed close reply with only ~42% of the expected audio bytes never starts the close grace', () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();
    driveToOneTurnBeforeClose(session, aai, clock);

    const lastLine = CALLER_LINES.at(-1)!;
    clock.now += 3000;
    aai.emit({ type: 'transcript.user', item_id: lastLine.id, text: lastLine.text });
    expect(session.last?.goal.code).toBe('CLOSE');
    const closeSentence = session.nextSpokenLine()!;

    clock.now += 500;
    aai.emit({ type: 'reply.started', reply_id: 'close-reply' });
    // ~42% of expected bytes, status completed -- mirrors the live incident where a folded
    // reply reported reply.done COMPLETED with the full transcript but only its first
    // segment's audio ever streamed (81,120/97 chars, 41.8%). Below the 50% floor.
    aai.emit({ type: 'reply.audio', data: Buffer.alloc(audioBytesFor(closeSentence, 0.42)).toString('base64') });
    aai.emit({ type: 'transcript.agent', item_id: 'close-t', text: closeSentence, reply_id: 'close-reply', interrupted: false });
    clock.now += 100;
    aai.emit({ type: 'reply.done', reply_id: 'close-reply', status: 'completed' });

    vi.advanceTimersByTime(5000);
    expect(sent.some((e) => e.type === 'ended')).toBe(false);
    expect(aai.isClosed).toBe(false);

    vi.advanceTimersByTime(40_000);
    expect(sent.at(-1)).toEqual({ type: 'ended', reason: 'close_timeout' });
    expect(aai.isClosed).toBe(true);
  });

  it('never starts the close grace before the close line\'s own reply.done arrives, even once its transcript already matches', () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();
    driveToOneTurnBeforeClose(session, aai, clock);

    const lastLine = CALLER_LINES.at(-1)!;
    clock.now += 3000;
    aai.emit({ type: 'transcript.user', item_id: lastLine.id, text: lastLine.text });
    expect(session.last?.goal.code).toBe('CLOSE');
    const closeSentence = session.nextSpokenLine();

    clock.now += 500;
    aai.emit({ type: 'reply.started', reply_id: 'close-reply' });
    const closeAudioBytes = audioBytesFor(closeSentence!, 1.0);
    aai.emit({ type: 'reply.audio', data: Buffer.alloc(closeAudioBytes).toString('base64') });
    // The full close sentence has already arrived and matches -- but this reply's own
    // reply.done has NOT fired yet.
    aai.emit({ type: 'transcript.agent', item_id: 'close-t', text: closeSentence!, reply_id: 'close-reply', interrupted: false });

    // Comfortably past CLOSE_GRACE_MS (1500ms) -- if the grace period had started from the
    // transcript match alone (the way legacy's own maybeArmCloseOnTranscript would, were it
    // not gated off in endpoint mode), the call would already have ended by now. It must
    // not: endpoint mode has exactly one place that starts the grace, and it requires
    // reply.done too.
    vi.advanceTimersByTime(5000);
    expect(sent.some((e) => e.type === 'ended')).toBe(false);
    expect(aai.isClosed).toBe(false);

    // reply.done lands only after this audio would have finished streaming -- same reasoning
    // as test (c) above, so the flat CLOSE_GRACE_MS is what governs the wait asserted below.
    clock.now += Math.ceil(audioPlaybackMs(closeAudioBytes)) + 100;
    // Now the reply.done arrives -- only now does the grace period begin.
    aai.emit({ type: 'reply.done', reply_id: 'close-reply', status: 'completed' });
    expect(sent.some((e) => e.type === 'ended')).toBe(false);
    vi.advanceTimersByTime(1500);
    expect(sent.at(-1)).toEqual({ type: 'ended', reason: 'agent_closed' });
  });

  it('the 45s CLOSE_TOTAL_MS hard cap still ends the call when the close line is never heard at all', () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock, brainMode: 'endpoint' });
    session.start();
    driveToOneTurnBeforeClose(session, aai, clock);

    const lastLine = CALLER_LINES.at(-1)!;
    clock.now += 3000;
    aai.emit({ type: 'transcript.user', item_id: lastLine.id, text: lastLine.text });
    expect(session.last?.goal.code).toBe('CLOSE'); // armClose() has now armed the 45s cap

    // No reply.started/transcript.agent/reply.done ever follows -- the audio was lost, or
    // the caller hung up first. Unchanged behavior: CLOSE_TOTAL_MS (45s) is the absolute
    // backstop regardless of brainMode.
    vi.advanceTimersByTime(44_999);
    expect(sent.some((e) => e.type === 'ended')).toBe(false);
    vi.advanceTimersByTime(1);
    expect(sent.at(-1)).toEqual({ type: 'ended', reason: 'close_timeout' });
    expect(aai.isClosed).toBe(true);
  });

  // Legacy contrast (CLAUDE.md LANE-FILES rule: "Legacy mode must be byte-for-byte
  // unchanged -- every new branch endpoint-only"). Direct-state construction -- the same
  // technique session.test.ts's own CLOSE describe blocks already use (see e.g. its
  // "reply.started labels a reply..." describe block's own doc comment) -- isolates the
  // mechanism itself rather than re-deriving four AUTOMATIC_REPLY_SETTLE_MS-paced turns just
  // to reach the same CLOSE goal legacy mode already has full live-drive coverage for
  // elsewhere. `session.last` is forced directly and `scheduleCloseIfNeeded` (the pre-
  // existing, UNTOUCHED-by-this-fix method) is called directly too, rather than through
  // `aai.emit` -- an emitted `reply.started`/`reply.done` falls through to that event's own
  // trailing `tick()`, which re-runs the REAL engine over the still-empty conversation log
  // and would clobber the forced CLOSE goal right back to INTAKE (exactly the pitfall
  // session.test.ts's own "pinning an unstable intermediate goal... does not survive a real
  // tick()" comment names). Proves legacy still reaches 'ended' via its own pre-existing
  // mechanism (`scheduleCloseIfNeeded` -> `beginCloseGrace`, its `brainMode === 'endpoint'`
  // guard unchanged), on the exact same `CLOSE_GRACE_MS` timing as endpoint mode's new path
  // above -- the two converge on the same observable behavior through entirely separate,
  // mode-gated mechanisms.
  it('legacy mode (brainMode omitted) still ends the call via its own pre-existing scheduleCloseIfNeeded/beginCloseGrace mechanism -- unaffected by the endpoint-mode fix above', () => {
    vi.useFakeTimers();
    const clock = { now: 0 };
    const aai = new FakeAaiSocket();
    const sent: ServerEvent[] = [];
    const session = newSession({ aai, sent, clock }); // brainMode omitted -- legacy, the default
    session.start();

    const closeHint = 'Your request is staged for independent approval. The payment is not released. Goodbye.';
    session.last = { ...session.last!, goal: { code: 'CLOSE', hint: closeHint, keyterms: [], turn_detection_hint: 'default' } };

    const internals = session as unknown as {
      replyTranscripts: Map<string, string>;
      replyAudioBytes: Map<string, number>;
      scheduleCloseIfNeeded: (replyId: string, status: string) => void;
    };
    const replyId = 'legacy-close-reply';
    internals.replyTranscripts.set(replyId, closeHint);
    // closeReplyHasEnoughAudio's own floor (CLOSE_AUDIO_BYTES_PER_CHAR * 0.5 per char) --
    // comfortably clears it, same margin session.test.ts's own CLOSE tests use.
    internals.replyAudioBytes.set(replyId, closeHint.length * 4_000);

    clock.now = 5100;
    internals.scheduleCloseIfNeeded(replyId, 'completed');

    expect(sent.some((e) => e.type === 'ended')).toBe(false);
    vi.advanceTimersByTime(1500); // CLOSE_GRACE_MS -- same constant, same mechanism as always
    expect(sent.at(-1)).toEqual({ type: 'ended', reason: 'agent_closed' });
    expect(aai.isClosed).toBe(true);
  });
});
